name: Publish
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type of release (major, minor, patch)"
        required: true
        default: ""

jobs:
  version:
    name: Version Increment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Git Config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Version increment
        run: npm version ${{ github.event.inputs.type }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: releases/${{ steps.package-version.outputs.current-version }}