name: Recreate develop branch

on:
  push:
    branches:
      - 'master'

jobs:
  recreate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create new develop branch
        run: |
          git checkout -b develop
          git push origin develop
