# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: octokit/request-action@v2.x
        id: get_profile
        with:
          route: GET /user
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
      - run: echo "Data ${{ fromJson(steps.get_profile.outputs.data).html_url }}"
        
