name: Update Tokens
on:
  repository_dispatch:
    types: [update-tokens]
jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save JSON data
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.tokenFileName }}
          json: ${{ github.event.client_payload.tokens }}
          dir: 'data'
        
      - name: Commit data
        run: |
          git config user.name 'Github update tokens'
          git config user.email '${{ secrets.ACTIONS_GIT_EMAIL }}'
          git add .
          git commit -am "Updated design tokens"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Open pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update to Tokens (${{ steps.date.outputs.date }})
          body: Tokens pushed from design
          branch: tokens-update

      - name: Log pull request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"